### ISSUE TITLE
No license for the razor-ssg template

### ISSUE THREAD

**Issue by zack4485** [NetCoreTemplates/razor-ssg#16]
There is currently no license for this repo.  This should be fixed quickly so that people know whether or not and how they can leverage this repo for their own projects.

I presume since it's a public repo the license would be some flavor of FOSS but an explicit license would make this more clear.

I would be happy to be added as a maintainer if you would like help!

**Comment by mythz** [comment]
Added the OSS BSD License in this commit:
https://github.com/NetCoreTemplates/razor-ssg/commit/5ee3f4bb892ff3befce113a286539114eeeff0d7

We try to keep this in sync with our primary https://servicestack.net website which is maintained at: https://github.com/ServiceStack/serviceStack.net

As such we're sensitive to disruptive changes, generally useful additive / non-breaking changes are welcome, so please open a discussion/PR for any major structural changes or big features so I can evaluate them before you invest any time/effort doing them.

Happy to keep accepting PRs in the short term, I can evaluate maintainer rights after assessing PRs to ensure they are in line with the template.
