### ISSUE TITLE
Clicking on anchor links results in header being hidden under banner

### ISSUE THREAD

**Issue by zack4485** [NetCoreTemplates/razor-ssg#20]
https://github.com/NetCoreTemplates/razor-ssg/blob/c105b3b64044273c59f26a9bc5ead1d5af87f310/MyApp/MarkdownPagesBase.cs#L367

Looks like there's a CSS issue causing the anchor link to scroll the page such that the clicked header is at the very top of the screen (obscured by the transparent banner).

This is a minor cosmetic issue and does not prevent the anchor links from working as intended, but it's certainly something worth fixing as part of the broader effort to make anchor links functional.

**Comment by zack4485** [comment]
@mythz the simple fix for this is to add the following...I'm not a Tailwind person so before I check anything in, would the proper place for this be the `typography.css` file?  Please note you may prefer a different amount of spacing above anchor links so `8rem` is just a suggestion.

```css
html {
	scroll-padding-top: 8rem;
}
```

**Comment by mythz** [comment]
Cheers, since it's site layout specific I've added it to _Layout.cshtml in this commit: https://github.com/NetCoreTemplates/razor-ssg/commit/e2447b0352665ec07cb3f5da6b8510a076c49bc6

**Comment by mythz** [comment]
I've also added some js which should fix anchor links to include the current page path since the template uses `<base href="/" >`. It looks like it's now working in blog posts, podcasts, documentation pages and top-level pages, so I think this is now resolved, thx!
